package: phpmailer_retry
version: '1.1.0'
author: 'Stefan Brinkers'
supportpage: https://github.com/anveno/phpmailer_retry

# Abhängigkeiten
# Anforderungen ans System oder anderere AddOns, um dieses AddOn installieren oder update zu können
requires:
  redaxo: '^5.11' # benötigt mindestens REDAXO 5.2
  php:
    version: '>=7.1' # benötigt mindestens PHP 7

page:
  hidden: true
